language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
script:
- flake8 .
deploy:
  - provider: heroku
    api_key:
      secure: x9X0PGznwE9+WI0D7KFwE44vf7A63/qM5QZ4qp+q7PSOgosa86nMMIP7Fv97hZ7IP8n4dhjDxyULx4PY5oKndyC4G67UJvlbEjWk8BoyCZOvQFdBsaxJTHut2VQprAKrTQ+0CKVyGNDVCB/SwjFTgGBk/q7fHxJQNhfQLXdDMfcoe7yIMzNrR1BUN4G6qBjSoIEJVzBQpfBvRYHPkWP5Ic38xJPlcddo8VoHIY5gYYaoOyh2hxperi2/KX53vYIco6cZi0PvbqhJ61DEY3VA8RYhGCuyvCf3g2Wiu4bCX6ndra/jtHjOVhf8kY+rgZDKCxDKiqxxGWH2ghp7OZRobW1P2hWc16RuSSfVAr5T1tIsU4khy0nwKNI53HzfvI7kF5CAoSNxyHftka48YNPc8OwtO9DsgWeieRpUeRkH3X5pjCXhvlfJZiRYGLDa/VvDZ6m6ODt9T6i2FCckkyRO0ecXvxheF8n2Ok8qj8iSHYt8ty8S3HN/1A6d/h2gvEWeBoZs2aUy3DgAB0XlDWirUGKeeC7MQ1GzL3qr1wDIRF8+xJiIBni+cVs/mD9AmmGdgh++C95pgXmURBCcGpK9eFsSyS1FKGJxSdC5cTyaFn5OfhgG6hGeKEH7ryLg6eepbSqFpbVSFYkRXYyJFhlqj5m8cNnWIfx8MMF/aIpDqxw=
    app: yogesh-portfolio
    on:
      branch: master
  - provider: heroku
    api_key:
      secure: dScOcsuFjLjiCYKPUdnF6XWHzL2nOPpRKK+d9M2++asLklWgJ2FO+qckU/1wm3iCO9x4MmnTXrwrmpCHXqmbc58uhJFES7zorthzMPntqwW6kdT0Ypy5ZiAr6GJ00dNI1Vqf++XCqD7FUzJYpKfzYjcW3GsUPxzPhzkXz1evzkz9dopwU8nPRp3EiEm3n2OfR+b1PpU64AMllsqSLzluSRv9aOD+dVufpvWvmSHXSa2iwlko/hYtxPzU++/rZUdbTkzivHYwdrc6/+MFw0o7z0y5febuWclRXisf05QHChBEiMeIZcvSGZhDrpHaxmOs24DEAEeJhtlbFwSH7Ds4k6AP3tFHvHGrYAtVCPdY5cO8wXL7q3NJOkCPXQbkrFrOG7LkIjHYRR6DYPL8LmBMA1d5M3aZBl0YOnvvkBYs8N5y/y5PhOEHb0aBEG35O3SoAuJeOLReW0R5oBUQfkEW3TIximwmoAUn4DytqgATRovGpi3y1D5uCTn32a0Nr+aOh1Jfrzk3u0+E2SglZ8PLn8hyK6Zoc87gzbox7kwaIE32oyvmPfBFIe3SOZ8RluQC6AVUQDtofivhtKQdVwfxpeGx2oEZ4no68+GGY/Mt6MyASC/JZmMmWnGG/7jsYscUrmzwyRB/Hxmc7/xUvUhA3d52u2OgaqhZxB1jPYnxzTU=
    app: yogesh-portfolio-stage
    on:
      branch: stage