language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
script:
- flake8 .
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: qxJzCcbs852BXuq0WU/13v1aVpN5JBAZbZU5Lh0b+I43qLYr9BVQHtSZmWcvZpQlCkUcNSSkgwthSv9HKNNmhbZ7lkz22aKwTQqGLWQ6suoo/bi/1eYqh65jdpNzTchUKo1/Gd1K8bMvzX5za7tUtkzP0VMbeg0YNm+zGiw7F+G9dDZOWF3+8ncxOo3f1c9uKlETpIetnaMQ7JpMCAmckYNJrcHdy+jQ58gyhgLG1whGvzYW4VC3QxEkSBkS7DhthIGWG4QPSf7puFzIyF2kKKWC/rDLZdEadHOiBZEI8PrTQMyfGqI64DnUwiTkIMin5e7TiMwcEeBsI6nN5xORx2nuZ1BDOn0EKaCYDsCzhRVFr0rZOcw0ao5HF7+mCCY95jIUKCXKwWT0kevhwtp13RP+NkpTHvE0MtUI5bJADrUl6kPhRP1PdftPdKwac5ERXDEN7oENkOSeUFGdqR5aP3jQMlvf+swYcWvi+IgUejZxdoU8OxovPuLrPQNBNEoAw+uQNOvTlVnsIWezBezC+e3y2BnHp1Snb9oPC6LPClOSpG9NZ0ca1LTTskquCAuAgbOCae1q+owHvOvRLAKDJ8CI/wwkOf3MzZzlV7AFT39RvWu6ULIrHbx7QHHP78kjKuhx2e7Eoq4lh/DWD2P2nZCTbiz5e0LYIlajYlHdO/Q=
    app: yogesh-portfolio
    on:
      branch: master
  - provider: heroku
    api_key:
      secure: nh2V1Fm6HmCWtaMbm+20g//qo4FG5gm1PHv74Zgup3+DxD8ANphITkYkIuG+xYvPzewjud8XK5MER8re9cv3EnN/WNQAinTgVHDSKwkEgclYftkmEsQ82sAarqnstfbSsC+2FAKNDveXz+4DjUdgTZos5pmFasKm7nu+++WWVG3UvxD5bTxOTyCNYjbkwo4QHm1HdmXZqAjT5WB300XSe/2t7CfYeaOQ4WUcaXyrCkkwEShAV4tbP75bN3M9Jfiry//3Rk74EQ4bSrrkjb49fThqFDH5fx9uu3RztdqNDacKQHQ2P+qhq2OgDnANvS8lerQ1sApSkSLfPNb/sJABPneu12yu6zp95oBetqHBq5K0McenSDwkvyZPp89x+qyiuRkWZsz6jJbNUlEhFnTNgOSTmmkQN1BjUAoEh0pJ3uUlzYPB748Kh4eZoIFKgDljCvnokhjYZ+CUTlGEwcqgb1iLvCCGJ7gbAU3JEEHeO3PEAGSTS3nLMyD56XtAFyCSWiUOhaGhUC5hqvZ0mUVLR7DZcX6xpF1m/OPVrgYYpTgfe+JwNj9RX0jQRV9AGwWU12saJgcQv3ci7UlTogZRSI/98s/VKaK0vL0i9uuWuD5yrNRzR38GQgSIt2JI0n3kT/eeTKCAQB+ui4+L9hI12Ts0JyHPD3BH+xt3V3EuCTc=
    app: yogesh-portfolio-stage
    on:
      branch: stage
